"""Generates a sample jobs_output.xlsx with realistic demo data."""
import sys
sys.path.insert(0, "/home/claude/job_scraper")
from scraper import save_to_excel

SAMPLE_JOBS = [
    {"id":"a1b2c3d4e5f6","source":"LinkedIn","title":"Senior Software Engineer","company":"Stripe","location":"Remote","salary":"$160,000 - $220,000","remote":"Yes","date_found":"2026-03-12","url":"https://linkedin.com/jobs/view/123","verified":"true","scam_flag":"","description":"Join Stripe's core payments team. 5+ years Python/Go. Distributed systems experience required. Equity + benefits."},
    {"id":"b2c3d4e5f6a7","source":"Indeed (software engineer)","title":"Full Stack Developer","company":"Notion","location":"San Francisco, CA","salary":"$130,000 - $170,000","remote":"Yes","date_found":"2026-03-12","url":"https://indeed.com/jobs/view/456","verified":"true","scam_flag":"","description":"Build features used by millions. React, Node.js, PostgreSQL. Hybrid or fully remote. Series C startup."},
    {"id":"c3d4e5f6a7b8","source":"RemoteOK","title":"Backend Engineer","company":"Shopify","location":"Remote","salary":"$140,000 - $190,000","remote":"Yes","date_found":"2026-03-11","url":"https://remoteok.com/jobs/789","verified":"true","scam_flag":"","description":"Scale our merchant platform. Ruby on Rails, Kubernetes, MySQL. Work from anywhere in the world."},
    {"id":"d4e5f6a7b8c9","source":"Google Alerts","title":"Data Scientist","company":"Airbnb","location":"Remote / New York","salary":"$150,000 - $200,000","remote":"Yes","date_found":"2026-03-11","url":"https://careers.airbnb.com/jobs/101","verified":"true","scam_flag":"","description":"Drive pricing and demand forecasting models. Python, Spark, SQL. PhD preferred but not required."},
    {"id":"e5f6a7b8c9d0","source":"Indeed (product manager)","title":"Senior Product Manager","company":"Figma","location":"San Francisco, CA","salary":"$170,000 - $230,000","remote":"No","date_found":"2026-03-10","url":"https://indeed.com/jobs/view/202","verified":"true","scam_flag":"","description":"Own the collaboration product roadmap. 5+ yrs PM experience. Design tool or SaaS background preferred."},
    {"id":"f6a7b8c9d0e1","source":"RemoteOK","title":"DevOps Engineer","company":"HashiCorp","location":"Remote","salary":"$130,000 - $160,000","remote":"Yes","date_found":"2026-03-10","url":"https://remoteok.com/jobs/303","verified":"true","scam_flag":"","description":"Build and maintain CI/CD infrastructure. Terraform, Kubernetes, AWS. Open source contributions valued."},
    {"id":"a7b8c9d0e1f2","source":"Google Alerts","title":"Machine Learning Engineer","company":"Hugging Face","location":"Remote","salary":"$160,000 - $210,000","remote":"Yes","date_found":"2026-03-09","url":"https://jobs.huggingface.co/111","verified":"true","scam_flag":"","description":"Train and deploy transformer models. PyTorch, CUDA, distributed training. Strong research background."},
    {"id":"b8c9d0e1f2a3","source":"Indeed (data scientist)","title":"Analytics Engineer","company":"dbt Labs","location":"Remote","salary":"$120,000 - $150,000","remote":"Yes","date_found":"2026-03-09","url":"https://indeed.com/jobs/view/404","verified":"true","scam_flag":"","description":"Build data models and analytics infrastructure. dbt, Snowflake, Looker. 3+ yrs analytics experience."},
    {"id":"c9d0e1f2a3b4","source":"LinkedIn","title":"Frontend Engineer","company":"Vercel","location":"Remote","salary":"$130,000 - $175,000","remote":"Yes","date_found":"2026-03-08","url":"https://linkedin.com/jobs/view/505","verified":"true","scam_flag":"","description":"Work on the Next.js ecosystem. TypeScript, React, WebAssembly. Passionate about developer experience."},
    {"id":"d0e1f2a3b4c5","source":"RemoteOK","title":"iOS Engineer","company":"Linear","location":"Remote","salary":"$140,000 - $180,000","remote":"Yes","date_found":"2026-03-08","url":"https://remoteok.com/jobs/606","verified":"true","scam_flag":"","description":"Build the iOS app used by top engineering teams. Swift, SwiftUI. Small team, high impact."},
    {"id":"e1f2a3b4c5d6","source":"Indeed (frontend developer)","title":"React Developer","company":"Unknown Recruiter","location":"Anywhere","salary":"","remote":"Yes","date_found":"2026-03-07","url":"https://indeed.com/jobs/view/707","verified":"false","scam_flag":"Vague company, no salary, suspicious requirements","description":"Earn $500/day working from home!! No experience needed. Just sign up and start today. Contact us now."},
    {"id":"f2a3b4c5d6e7","source":"Google Alerts","title":"Staff Engineer","company":"Cloudflare","location":"Remote / Austin, TX","salary":"$200,000 - $280,000","remote":"Yes","date_found":"2026-03-07","url":"https://careers.cloudflare.com/jobs/808","verified":"true","scam_flag":"","description":"Lead technical direction for our edge network. Distributed systems, Rust or C++, 10+ yrs experience."},
]

save_to_excel(SAMPLE_JOBS, "/mnt/user-data/outputs/jobs_output.xlsx")
print("Demo Excel created!")
